title: beCloudReady
author:
  name: 'Kumar Yashojeet'
  email: yash@becloudready.com
taxonomies:
  - category
  - tag
metadata:
  description: 'beCloudready provides you DevOps Solution'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
email: your-email@domain.com
description: 'blogging is fun'
social:
  -
    url: 'https://www.facebook.com/becloudready/'
    icon: facebook
  -
    url: 'https://twitter.com/becloudready'
    icon: twitter
  -
    url: '#'
    icon: google-plus
footer:
  text: 'All Right Reserved © beCloudready.com '
  address:
    title: 'COME VISIT'
    lines:
      -
        line: Canada
  social_title: Socialize
  contact:
    title: 'CONTACT US'
    lines:
      -
        text: 'Chandan Kumar'
        url: 'https://www.facebook.com/chandank3'
      -
        text: 'Kumar Yashojeet'
        url: 'https://www.facebook.com/yasho.munshi'
      -
        text: chandank.kumar@gmail.com
      -
        text: yash@becloudready.com
